name: Rebuild website static
on:
  push:
    branches: [main]
jobs:
  trigger:
    runs-on: ubuntu-latest
    steps:
      - run: curl -fsS -X POST "${{ secrets.VERCEL_DEPLOY_HOOK }}?buildCache=false"
